Algoritmo "Exercício 1"

Var
// Seção de Declarações das variáveis 
nome: caractere
ano_at, ano_no, idade: inteiro

Inicio

      escreva ("Digite seu nome")
      leia(nome)
      
      escreval("Digite o ano de seu nascimento")
      leia (ano_no)
      
      escreva ("Digite o ano atual")
      leia (ano_at)
      
      idade <- ano_at - ano_no
      
      escreva ("Seu nome e ", nome)

      

      
// Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo